import = [
	"~/.config/alacritty/colors.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
